#!/bin/sh

[ "x$IFACE" = "xlo" ] && exit 0
[ "x$IFACE" = "x--all" ] && exit 0
grep -Eq '^iface  *'${IFACE}'  *inet6  *' /etc/network/interfaces && exit 0

if [ -f /var/run/odhcp6c.${IFACE}.pid ]; then
    pid=$(cat /var/run/odhcp6c.${IFACE}.pid)
    kill -9 "$pid" 2>/dev/null
fi

exit 0

