# Creates the "feed", packages not required for the image
# but that should be built for the feed so that other
# components may use them and install on demand.

# We have a GPL-2.0-only license for this recipe...
require conf/license/openpli-gplv2.inc

# Depend on the image, so that it gets build
DEPENDS = "openpli-enigma2-image package-index-feed"

PROVIDES = "${PN} \
	enigma2-plugin-extensions-fancontrol2 \
	"

OPTIONAL_PACKAGES_BROKEN = ""
OPTIONAL_PACKAGES ?= ""
OPTIONAL_BSP_PACKAGES ?= ""
OPTIONAL_PACKAGES += " \
	autofs \
	astra-sm \
	autossh \
	bitratecalc \
	btrfs-tools \
	ccid \
	ctorrent \
	cups \
	davfs2 \
	diffutils \
	dabstreamer \
	dosfstools \
	dvb-apps \
	dvblast \
	dvbsnoop \
	dvdfs \
	edid-decode \
	dnscrypt-proxy \
	eti-tools \
	evtest \
	exfatprogs \
	exteplayer3 \
	f2fs-tools \
	fio \
	gdb \
	gerbera \
	grep \
	gstplayer \
	gstplayer2 \
	hddtemp \
	hdparm \
	htop \
	flip \
	ifuse \
	inadyn-mt \
	inetutils \
	iperf3 \
	ipkg-tools \
	iproute2 \
	iputils \
	joe \
	less \
	lsdir \
	libbluray \
	libudfread \
	mc \
	mediainfo \
	minisatip \
	mpd \
	mtd-utils \
	mtools \
	mtr \
	nano \
	net-tools \
	ntfs-3g \
	ntp \
	nodejs \
	openmultiboot \
	ofgwrite \
	openresolv \
	openssh \
	openvpn \
	libpcsc-perl \
	parted \
	picocom \
	ppp \
	pv \
	pyload \
	python3-future \
	python3-fuzzywuzzy \
	python3-beautifulsoup4 \
	python3-js2py \
	python3-ujson \
	python3-lxml \
	python3-levenshtein \
	python3-mechanize \
	python3-tmdbsimple \
	python3-ntplib \
	python3-puremagic \
	python3-pysnmp \
	python3-requests \
	python3-tinytag \
	python3-transmission-rpc \
	python3-tqdm \
	python3-yenc \
	python3-youtube-dl \
	python3-aws-iot-device-sdk-python \
	rclone \
	rsync \
	rtl-sdr \
	rtorrent \
	sabnzbd \
	samba \
	satipclient \
	satpi \
	screen \
	sed \
	shairplay \
	smartmontools \
	smbnetfs \
	sshpass \
	strace \
	streamlinksrv \
	streamlink \
	tsniv2ni \
	tcpdump \
	tmux \
	transmission \
	tsanalyze \
	tsduck \
	mediamtx \
	udpxy \
	upx \
	ubuntu-font-family \
	ushare \
	v4l-utils \
	vim \
	wget \
	wscan \
	wireless-tools \
	xfsprogs \
	yafc \
	zeroconf \
	zerotier \
	zip \
	zsh \
	eplayer5 \
	enigma2-plugin-drivers-network-usb-ath9k-htc \
	enigma2-plugin-drivers-network-usb-r8723a \
	enigma2-plugin-drivers-network-usb-rt8723bs \
	enigma2-plugin-drivers-network-usb-ax88179-178a \
	enigma2-plugin-drivers-network-usb-rtl8192ce \
	enigma2-plugin-drivers-network-usb-rt3070 \
	enigma2-plugin-drivers-network-usb-rt3573 \
	enigma2-plugin-drivers-network-usb-asix \
	enigma2-plugin-drivers-network-usb-rt2800 \
	enigma2-plugin-drivers-network-usb-mt7610u \
	enigma2-plugin-drivers-network-usb-r8712u \
	enigma2-plugin-drivers-network-usb-rt5572 \
	enigma2-plugin-drivers-network-usb-rtl8188fu \
	enigma2-plugin-drivers-network-usb-rtl8192eu \
	enigma2-plugin-drivers-network-usb-rtl8192fu \
	enigma2-plugin-drivers-network-usb-rtl8814au \
	enigma2-plugin-drivers-network-usb-rtl8821cu \
	enigma2-plugin-drivers-network-usb-rtl8822bu \
	enigma2-plugin-drivers-network-usb-smsc75xx \
	${OPTIONAL_BSP_PACKAGES} \
	"

ALLIANCE_PLUGINS = " \
	enigma2-3rdparty-plugins \
	enigma2-plugin-extensions-autoblchanger \
	enigma2-plugin-extensions-autobouquets \
	enigma2-plugin-extensions-bouquetcleanup \
	enigma2-plugin-extensions-chefkoch \
	enigma2-plugin-extensions-chocholousek-picons \
	enigma2-plugin-extensions-clevertanken \
	enigma2-plugin-extensions-dlnabrowser \
	enigma2-plugin-extensions-e2m3u2bouquet \
	enigma2-plugin-extensions-e2piconizer \
	enigma2-plugin-extensions-epgtranslator \
	enigma2-plugin-extensions-forcefbclnbpower \
	enigma2-plugin-extensions-fempa \
	enigma2-plugin-extensions-gerbera \
	enigma2-plugin-extensions-infobartunerstate \
	enigma2-plugin-extensions-lamedbmerger \
	enigma2-plugin-extensions-lottoextended \
	enigma2-plugin-extensions-mediatomb \
	enigma2-plugin-extensions-multiquickbutton \
	enigma2-plugin-extensions-oscamsmartcard \
	enigma2-plugin-extensions-ondemand \
	enigma2-plugin-extensions-piconmanager \
	enigma2-plugin-extensions-piconsmissing\
	enigma2-plugin-extensions-piconsupdater \
	enigma2-plugin-extensions-picturecenterfs \
	enigma2-plugin-extensions-remotechannelstreamconverter \
	enigma2-plugin-extensions-streamtv \
	enigma2-plugin-extensions-tuxcom \
	enigma2-plugin-extensions-tuxterm \
	enigma2-plugin-extensions-tvspielfilm \
	enigma2-plugin-extensions-tunerserver \
	enigma2-plugin-extensions-witaispeechtotext \
	enigma2-plugin-extensions-xmodem \
	enigma2-plugin-systemplugins-3gmodemmanager \
	enigma2-plugin-systemplugins-aboutboxbranding \
	enigma2-plugin-systemplugins-abmcustommiximporter \
	enigma2-plugin-systemplugins-channelsimporter \
	enigma2-plugin-systemplugins-micomupgrade \
	enigma2-plugin-systemplugins-multitranscodingsetup \
	enigma2-plugin-systemplugins-radiotimesemulator \
	enigma2-plugin-systemplugins-remotecontrolselection \
	enigma2-plugin-systemplugins-satscanlcn \
	enigma2-plugin-systemplugins-wanip \
	enigma2-plugin-systemplugins-wirelessaccesspoint \
	"

OPTIONAL_BSP_ENIGMA2_PACKAGES ?= ""
ENIGMA2_OPTIONAL = " \
	channelsettings-enigma2-meta \
	dvb-usb-drivers-meta \
	enigma2-binary-plugins \
	enigma2-display-skins \
	enigma2-plugin-skins-e2darkos \
	enigma2-plugin-skins-aglare \
	enigma2-plugin-skins-octetfhd \
	enigma2-plugin-skins-pd1loi-hd-night \
	enigma2-plugin-skins-pli-hd \
	enigma2-plugin-skins-pli-hd-fullnight \
	enigma2-plugin-skins-simple-gray \
	enigma2-plugin-skins-ax-blue-fhd \
	enigma2-plugin-skins-blueaccents-fhd \
	enigma2-plugin-skins-blue-line-oe \
	enigma2-plugin-skins-gradient-fhd \
	enigma2-plugin-skins-glamouraurafhd \
	enigma2-plugin-skins-madmax-impossible \
	enigma2-plugin-skins-steampunk \
	enigma2-plugin-security-firewall \
	enigma2-plugin-drivers-usbserial \
	enigma2-plugin-extensions-arabicsavior \
	enigma2-plugin-extensions-backupflash \
	enigma2-plugin-extensions-dlnaserver \
	enigma2-plugin-extensions-e2embyclient \
	enigma2-plugin-extensions-keyadder \
	enigma2-plugin-extensions-raedquicksignal \
	enigma2-plugin-extensions-backupsuite \
	enigma2-plugin-extensions-autobouquets \
	enigma2-plugin-extensions-bouquetmakerxtream \
	enigma2-plugin-extensions-e2iplayer \
	enigma2-plugin-extensions-e2iplayer-deps \
	enigma2-plugin-extensions-enhancedmoviecenter \
	enigma2-plugin-extensions-foreca \
	enigma2-plugin-extensions-hetweer \
	enigma2-plugin-extensions-ppanel \
	enigma2-plugin-extensions-serienrecorder \
	enigma2-plugin-extensions-oscamstatus \
	enigma2-plugin-extensions-sdgradio \
	enigma2-plugin-extensions-subssupport \
	enigma2-plugin-extensions-xklass \
	enigma2-plugin-extensions-xtraevent \
	enigma2-plugin-extensions-enigmalight \
	enigma2-plugin-extensions-enigmawelt \
	enigma2-plugin-extensions-fontinfo \
	enigma2-plugin-extensions-freechannels \
	enigma2-plugin-extensions-fritzcall \
	enigma2-plugin-extensions-infobarweather \
	enigma2-plugin-extensions-iptv-org-playlists \
	enigma2-plugin-extensions-managerautofs \
	enigma2-plugin-extensions-mediaplayer2 \
	enigma2-plugin-extensions-modifyplifullhd \
	enigma2-plugin-extensions-jediepgxtream \
	enigma2-plugin-extensions-moviemanager \
	enigma2-plugin-extensions-oaweather \
	enigma2-plugin-extensions-openmultiboot \
	enigma2-plugin-extensions-refreshbouquet \
	enigma2-plugin-extensions-weathermsn \
	enigma2-plugin-extensions-xmodem \
	enigma2-plugin-extensions-xstreamity \
	enigma2-plugin-extensions-automatic-fullbackup \
	enigma2-plugin-extensions-historyzapselector \
	enigma2-plugin-extensions-sundtekcontrolcenter \
	enigma2-plugin-extensions-ts-sateditor \
	enigma2-plugin-extensions-vavoo \
	enigma2-plugin-extensions-vcs \
	enigma2-plugin-extensions-skymultiview \
	enigma2-plugin-extensions-xmodem \
	enigma2-plugin-extensions-yahooweather \
	enigma2-plugin-extensions-yampmusicplayer \
	enigma2-plugin-extensions-weatherplugin \
	enigma2-plugin-extensions-plutotv \
	enigma2-plugin-extensions-estalker \
	enigma2-plugin-systemplugins-m3uiptv \
	enigma2-plugin-systemplugins-netspeedtest \
	enigma2-plugin-systemplugins-extnumberzap \
	enigma2-plugin-systemplugins-extrafancontrol \
	enigma2-plugin-systemplugins-mountmanager \
	enigma2-plugin-systemplugins-signalfinder \
	enigma2-plugin-systemplugins-terrestrialbouquet \
	enigma2-plugin-systemplugins-crossepg \
	enigma2-plugin-systemplugins-hrtunerproxy \
	enigma2-plugin-systemplugins-misplslcnscan \
	enigma2-plugin-systemplugins-newvirtualkeyboard \
	enigma2-plugin-systemplugins-satipserver \
	enigma2-plugin-systemplugins-serviceapp \
	${@bb.utils.contains_any("MACHINE_FEATURES", "kodi22", "kodi-addons-meta enigma2-plugin-extensions-kodi", "", d)} \
	alsa-plugins \
	enigma2-plugins \
	meta-enigma2-dvdburn \
	packagegroup-openplugins \
	picons-enigma2-meta \
	softcams-enigma2-meta \
	enigma2-plugins-alliance \
	${ALLIANCE_PLUGINS} \
	${OPTIONAL_BSP_ENIGMA2_PACKAGES} \
	"

DEPENDS += "${OPTIONAL_PACKAGES} ${ENIGMA2_OPTIONAL}"
